services:
  - type: static_site
    name: cerro-largo-frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: VITE_API_URL
        value: https://cerro-largo-backend.onrender.com
